name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone repository if not present, or pull if already cloned
      run: |
        if [ ! -d "/srv/fradgify/.git" ]; then
          # Clone the repo if it doesn't exist
          git clone https://github.com/Fradge26/fradgify.git /srv/fradgify
        fi
        # Navigate to the directory
        cd /srv/fradgify
        # Pull the latest changes from the develop branch
        git pull origin develop
