name: Deploy to Fradgify Dev Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone repository if not present, or pull if already cloned
      run: |
        if [ ! -d "/srv/fradgify/.git" ]; then
          # Clone the repo if it doesn't exist
          git clone https://github.com/Fradge26/fradgify.git /srv/fradgify
        fi
        # Add /srv/fradgify as a safe directory for Git
        git config --global --add safe.directory /srv/fradgify
        # Navigate to the directory
        cd /srv/fradgify
        # Pull the latest changes from the develop branch
        git pull origin develop

    - name: Set up Python environment
      run: |
        cd /srv/fradgify
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Enable Apache mods
      run: |
        sudo a2enmod rewrite
        sudo a2enmod ssl
        sudo a2enmod headers
        sudo a2enmod cgi

    - name: Deploy site files
      run: |
        sudo mkdir -p /var/www/fradgify.kozow.com/flask_app
        sudo mkdir -p /var/www/fradgify.kozow.com/static
        sudo rsync -av --delete /srv/fradgify/flask_app/ /var/www/fradgify.kozow.com/flask_app/
        sudo rsync -av --delete /srv/fradgify/static/ /var/www/fradgify.kozow.com/static/
        sudo cp /srv/fradgify/apache/flask_app.wsgi /var/www/fradgify.kozow.com/flask_app/flask_app.wsgi

    - name: Load Apache conf
      run: |
        sudo cp /srv/fradgify/apache/fradgify.kozow.com.conf /etc/apache2/sites-available/fradgify.kozow.com.conf
        sudo a2ensite fradgify.kozow.com.conf
        sudo systemctl reload apache2
