name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: >
          ssh -o StrictHostKeyChecking=no deploy_user@${{ secrets.APACHE_TFL_IP }} "cd /var/www/tfl_modelling_tools && git pull origin develop && source ~/venv/bin/activate && pip install -r requirements.txt && sudo cp web_app/conf/tfl_modelling_tools.conf /etc/apache2/sites-available && sudo a2ensite tfl_modelling_tools && sudo systemctl reload apache2"

